// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package config

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetAllConfigKeys(ctx context.Context) ([]string, error)
	// Config queries
	GetConfigValue(ctx context.Context, key string) (sql.NullString, error)
	SetConfigValue(ctx context.Context, arg SetConfigValueParams) error
}

var _ Querier = (*Queries)(nil)
