// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package whatsapp

import (
	"context"
)

type Querier interface {
	DeleteWhatsappMessagesByConversation(ctx context.Context, conversationID string) error
	GetAllConversationIDs(ctx context.Context) ([]string, error)
	GetLatestWhatsappMessage(ctx context.Context, conversationID string) (WhatsappMessage, error)
	GetWhatsappMessageCount(ctx context.Context, conversationID string) (int64, error)
	GetWhatsappMessagesByConversation(ctx context.Context, conversationID string) ([]WhatsappMessage, error)
	// WhatsApp message queries
	InsertWhatsappMessage(ctx context.Context, arg InsertWhatsappMessageParams) error
}

var _ Querier = (*Queries)(nil)
