apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: suffix
suffix: ${environmentSuffix}
fieldSpecs:
- path: metadata/name
- path: metadata/labels/instance
- path: metadata/labels/app.kubernetes.io\/instance
- group: apps
  path: spec/selector/matchLabels/instance
- group: apps
  path: spec/selector/matchLabels/app.kubernetes.io\/instance
- group: apps
  path: spec/template/metadata/labels/instance
- group: apps
  path: spec/template/metadata/labels/app.kubernetes.io\/instance
- group: apps
  path: spec/template/spec/affinity/podAffinity/preferredDuringSchedulingIgnoredDuringExecution/podAffinityTerm/labelSelector/matchLabels/instance
- group: apps
  path: spec/template/spec/affinity/podAffinity/preferredDuringSchedulingIgnoredDuringExecution/podAffinityTerm/labelSelector/matchLabels/app.kubernetes.io\/instance
- group: apps
  path: spec/template/spec/affinity/podAffinity/requiredDuringSchedulingIgnoredDuringExecution/labelSelector/matchLabels/instance
- group: apps
  path: spec/template/spec/affinity/podAffinity/requiredDuringSchedulingIgnoredDuringExecution/labelSelector/matchLabels/app.kubernetes.io\/instance
- group: apps
  path: spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/podAffinityTerm/labelSelector/matchLabels/instance
- group: apps
  path: spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/podAffinityTerm/labelSelector/matchLabels/app.kubernetes.io\/instance
- group: apps
  path: spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/labelSelector/matchLabels/instance
- group: apps
  path: spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/labelSelector/matchLabels/app.kubernetes.io\/instance
- group: apps
  path: spec/template/spec/containers/envFrom/configMapRef/name
- group: apps
  path: spec/template/spec/containers/envFrom/secretRef/name
- group: apps
  path: spec/template/spec/topologySpreadConstraints/labelSelector/matchLabels/instance
- group: apps
  path: spec/template/spec/topologySpreadConstraints/labelSelector/matchLabels/app.kubernetes.io\/instance
- kind: PodDisruptionBudget
  path: spec/selector/matchLabels/app.kubernetes.io\/instance
- kind: Service
  path: spec/selector/app.kubernetes.io\/instance
- kind: VaultAuth
  path: spec/jwt/serviceAccount
- kind: VaultStaticSecret
  path: spec/destination/name
- kind: VaultStaticSecret
  path: spec/rolloutRestartTargets/name
- kind: VaultStaticSecret
  path: spec/vaultAuthRef
- kind: VirtualService
  path: spec/http/name
- kind: VirtualService
  path: spec/http/route/destination/host
- kind: VirtualService
  path: spec/tcp/route/destination/host
