apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: tenant
  labels:
    environment: ${environmentInstance}
    part-of: &partOf ${tenant}
    app.kubernetes.io/part-of: *partOf
spec:
  vaultAuthGlobalRef:
    name: eternis
    namespace: tenants
  jwt:
    role: ${tenant}-${environment}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: &name tenant
  labels:
    environment: ${environmentInstance}
    part-of: &partOf ${tenant}
    app.kubernetes.io/part-of: *partOf
spec:
  vaultAuthRef: *name
  type: kv-v2
  mount: eternis
  path: ${environment}/${tenant}/shared
  destination:
    name: *name
    create: true
  rolloutRestartTargets:
  - kind: StatefulSet
    name: telegram-chat
  refreshAfter: 10m
