// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/EternisAI/enchanted-twin/pkg/agent/memory/evolvingmemory/storage/types"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type DocumentChunk struct {
	ID                 pgtype.UUID         `json:"id"`
	Content            string              `json:"content"`
	ContentVector      *pgvector_go.Vector `json:"contentVector"`
	ChunkIndex         int32               `json:"chunkIndex"`
	OriginalDocumentID string              `json:"originalDocumentId"`
	Source             string              `json:"source"`
	FilePath           pgtype.Text         `json:"filePath"`
	Tags               []string            `json:"tags"`
	MetadataJson       []byte              `json:"metadataJson"`
	CreatedAt          time.Time           `json:"createdAt"`
}

type MemoryFact struct {
	ID                  pgtype.UUID                   `json:"id"`
	Content             string                        `json:"content"`
	ContentVector       *pgvector_go.Vector           `json:"contentVector"`
	Timestamp           time.Time                     `json:"timestamp"`
	Source              string                        `json:"source"`
	Tags                []string                      `json:"tags"`
	DocumentReferences  []string                      `json:"documentReferences"`
	MetadataJson        []byte                        `json:"metadataJson"`
	FactCategory        pgtype.Text                   `json:"factCategory"`
	FactSubject         types.NullableSanitizedString `json:"factSubject"`
	FactAttribute       pgtype.Text                   `json:"factAttribute"`
	FactValue           pgtype.Text                   `json:"factValue"`
	FactTemporalContext pgtype.Text                   `json:"factTemporalContext"`
	FactSensitivity     pgtype.Text                   `json:"factSensitivity"`
	FactImportance      pgtype.Int4                   `json:"factImportance"`
	FactFilePath        pgtype.Text                   `json:"factFilePath"`
	CreatedAt           time.Time                     `json:"createdAt"`
}

type SourceDocument struct {
	ID           pgtype.UUID `json:"id"`
	Content      string      `json:"content"`
	ContentHash  string      `json:"contentHash"`
	DocumentType string      `json:"documentType"`
	OriginalID   string      `json:"originalId"`
	MetadataJson []byte      `json:"metadataJson"`
	CreatedAt    time.Time   `json:"createdAt"`
}
