// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package holons

import (
	"context"
)

type Querier interface {
	AddUserToHolon(ctx context.Context, arg AddUserToHolonParams) error
	CheckUserInHolon(ctx context.Context, arg CheckUserInHolonParams) (int64, error)
	// Author queries
	CreateOrUpdateAuthor(ctx context.Context, arg CreateOrUpdateAuthorParams) error
	CreateThread(ctx context.Context, arg CreateThreadParams) error
	CreateThreadMessage(ctx context.Context, arg CreateThreadMessageParams) error
	EnsureAuthorExists(ctx context.Context, arg EnsureAuthorExistsParams) error
	GetAuthor(ctx context.Context, identity string) (Author, error)
	GetHolonByIdentifier(ctx context.Context, arg GetHolonByIdentifierParams) (string, error)
	GetThread(ctx context.Context, id string) (GetThreadRow, error)
	GetThreadMessage(ctx context.Context, id string) (GetThreadMessageRow, error)
	// Thread message queries
	GetThreadMessages(ctx context.Context, threadID string) ([]GetThreadMessagesRow, error)
	// Thread queries
	GetThreads(ctx context.Context, arg GetThreadsParams) ([]GetThreadsRow, error)
	// Holon queries
	GetUserHolons(ctx context.Context, authorIdentity string) ([]string, error)
	IncrementThreadViews(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
