/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HolonIndexRouteImport } from './routes/holon/index'
import { Route as SettingsPermissionsRouteImport } from './routes/settings.permissions'
import { Route as SettingsDataSourcesRouteImport } from './routes/settings.data-sources'
import { Route as SettingsCustomizeRouteImport } from './routes/settings.customize'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as HolonThreadIdRouteImport } from './routes/holon/$threadId'
import { Route as ChatChatIdRouteImport } from './routes/chat/$chatId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HolonIndexRoute = HolonIndexRouteImport.update({
  id: '/holon/',
  path: '/holon/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataSourcesRoute = SettingsDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomizeRoute = SettingsCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const HolonThreadIdRoute = HolonThreadIdRouteImport.update({
  id: '/holon/$threadId',
  path: '/holon/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/holon/$threadId': typeof HolonThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/customize': typeof SettingsCustomizeRoute
  '/settings/data-sources': typeof SettingsDataSourcesRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/holon': typeof HolonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/holon/$threadId': typeof HolonThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/customize': typeof SettingsCustomizeRoute
  '/settings/data-sources': typeof SettingsDataSourcesRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/holon': typeof HolonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/holon/$threadId': typeof HolonThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/customize': typeof SettingsCustomizeRoute
  '/settings/data-sources': typeof SettingsDataSourcesRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/holon/': typeof HolonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/chat/$chatId'
    | '/holon/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/customize'
    | '/settings/data-sources'
    | '/settings/permissions'
    | '/holon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/chat/$chatId'
    | '/holon/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/customize'
    | '/settings/data-sources'
    | '/settings/permissions'
    | '/holon'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/chat/$chatId'
    | '/holon/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/customize'
    | '/settings/data-sources'
    | '/settings/permissions'
    | '/holon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TasksRoute: typeof TasksRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  HolonThreadIdRoute: typeof HolonThreadIdRoute
  HolonIndexRoute: typeof HolonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holon/': {
      id: '/holon/'
      path: '/holon'
      fullPath: '/holon'
      preLoaderRoute: typeof HolonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data-sources': {
      id: '/settings/data-sources'
      path: '/data-sources'
      fullPath: '/settings/data-sources'
      preLoaderRoute: typeof SettingsDataSourcesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/customize': {
      id: '/settings/customize'
      path: '/customize'
      fullPath: '/settings/customize'
      preLoaderRoute: typeof SettingsCustomizeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/holon/$threadId': {
      id: '/holon/$threadId'
      path: '/holon/$threadId'
      fullPath: '/holon/$threadId'
      preLoaderRoute: typeof HolonThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsCustomizeRoute: typeof SettingsCustomizeRoute
  SettingsDataSourcesRoute: typeof SettingsDataSourcesRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsCustomizeRoute: SettingsCustomizeRoute,
  SettingsDataSourcesRoute: SettingsDataSourcesRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TasksRoute: TasksRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  HolonThreadIdRoute: HolonThreadIdRoute,
  HolonIndexRoute: HolonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
