// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

// NetworkMessage represents a single message in the twin network.
// The DateTime scalar re-uses the same string-based representation as the main API.
type NetworkMessage struct {
	ID           string `json:"id"`
	AuthorPubKey string `json:"authorPubKey"`
	NetworkID    string `json:"networkID"`
	ThreadID     string `json:"threadID"`
	Content      string `json:"content"`
	CreatedAt    string `json:"createdAt"`
	IsMine       bool   `json:"isMine"`
	Signature    string `json:"signature"`
}

type NetworkThread struct {
	ID           string            `json:"id"`
	UpdatedAt    string            `json:"updatedAt"`
	Messages     []*NetworkMessage `json:"messages"`
	AuthorPubKey string            `json:"authorPubKey"`
}

type Query struct {
}
