package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"time"

	twinnetwork "github.com/EternisAI/enchanted-twin/twin_network"
	"github.com/EternisAI/enchanted-twin/twin_network/graph/model"
)

// PostMessage is the resolver for the postMessage field.
func (r *mutationResolver) PostMessage(ctx context.Context, authorPubKey string, networkID string, text string) (*model.NetworkMessage, error) {
	msg := twinnetwork.NetworkMessage{
		AuthorPubKey: authorPubKey,
		NetworkID:    networkID,
		Text:         text,
		CreatedAt:    time.Now().UTC(),
	}
	r.Store.Add(msg)

	return &model.NetworkMessage{
		AuthorPubKey: msg.AuthorPubKey,
		NetworkID:    msg.NetworkID,
		Text:         msg.Text,
		CreatedAt:    msg.CreatedAt.Format(time.RFC3339),
	}, nil
}

// GetNewMessages is the resolver for the getNewMessages field.
func (r *queryResolver) GetNewMessages(ctx context.Context, networkID string, fromID int, limit *int) ([]*model.NetworkMessage, error) {
	msgs := r.Store.GetSince(networkID, int64(fromID), limit)

	out := make([]*model.NetworkMessage, len(msgs))
	for i, m := range msgs {
		out[i] = &model.NetworkMessage{
			ID:           fmt.Sprintf("%d", m.ID),
			AuthorPubKey: m.AuthorPubKey,
			NetworkID:    m.NetworkID,
			Text:         m.Text,
			CreatedAt:    m.CreatedAt.Format(time.RFC3339),
		}
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
