// Code generated by component-generator. DO NOT EDIT.

package bootstrap

// RegisterAllKnownComponents registers all components discovered in the codebase
func RegisterAllKnownComponents(loggerFactory *LoggerFactory) {

	// AI components
	loggerFactory.ForAI("ai.completions") // pkg/bootstrap/fx/ai.go:60
	loggerFactory.ForAI("ai.embeddings") // pkg/bootstrap/fx/ai.go:85
	loggerFactory.ForAI("ai.service") // pkg/bootstrap/components_generated.go:11

	// Anonymizer components
	loggerFactory.ForAnonymizer("ai.anonymizer") // pkg/bootstrap/components_generated.go:14

	// Database components
	loggerFactory.ForDatabase("database.postgresql") // pkg/bootstrap/components_generated.go:17
	loggerFactory.ForDatabase("sqlite.queries") // pkg/bootstrap/fx/infrastructure.go:155
	loggerFactory.ForDatabase("sqlite.store") // pkg/bootstrap/fx/infrastructure.go:126

	// Directory components
	loggerFactory.ForDirectory("directory.watcher") // pkg/bootstrap/components_generated.go:22

	// Embedding components
	loggerFactory.ForEmbedding("embedding.wrapper") // pkg/bootstrap/fx/database.go:36

	// MCP components
	loggerFactory.ForMCP("mcp.service") // pkg/bootstrap/components_generated.go:28

	// Manager components
	loggerFactory.ForManager("holon.manager") // pkg/holon/manager.go:79

	// Memory components
	loggerFactory.ForMemory("evolving.memory") // pkg/bootstrap/fx/memory.go:36
	loggerFactory.ForMemory("memory.storage") // pkg/bootstrap/fx/database.go:62

	// NATS components
	loggerFactory.ForNATS("nats.client") // pkg/bootstrap/fx/infrastructure.go:99
	loggerFactory.ForNATS("nats.server") // pkg/bootstrap/fx/infrastructure.go:78

	// Repository components
	loggerFactory.ForRepository("chat.repository") // pkg/bootstrap/fx/services.go:59

	// Server components
	loggerFactory.ForServer("graphql.server") // pkg/bootstrap/components_generated.go:45

	// Service components
	loggerFactory.ForService("holon.service.main") // pkg/holon/service.go:46

	// TTS components
	loggerFactory.ForTTS("tts.service") // pkg/bootstrap/fx/services.go:124

	// Telegram components
	loggerFactory.ForTelegram("telegram.service") // pkg/bootstrap/components_generated.go:54

	// Temporal components
	loggerFactory.ForTemporal("temporal.client") // pkg/bootstrap/fx/temporal.go:53
	loggerFactory.ForTemporal("temporal.scheduler") // pkg/bootstrap/components_generated.go:58
	loggerFactory.ForTemporal("temporal.worker") // pkg/bootstrap/components_generated.go:59

	// TwinChat components
	loggerFactory.ForTwinChat("twinchat.service") // pkg/bootstrap/components_generated.go:62

	// Utility components
	loggerFactory.ForComponent("fx.framework") // pkg/bootstrap/components_generated.go:65
	loggerFactory.ForComponent("infrastructure.config") // pkg/bootstrap/fx/infrastructure.go:59
	loggerFactory.ForComponent("infrastructure.main") // pkg/bootstrap/components_generated.go:67
	loggerFactory.ForComponent("main.startup") // pkg/bootstrap/components_generated.go:68
	loggerFactory.ForComponent("services.background") // pkg/bootstrap/components_generated.go:69
	loggerFactory.ForComponent("tools.application") // pkg/bootstrap/components_generated.go:70
	loggerFactory.ForComponent("tools.registry") // pkg/bootstrap/components_generated.go:71

	// WhatsApp components
	loggerFactory.ForWhatsApp("whatsapp.service") // pkg/bootstrap/components_generated.go:74
}

// ComponentCatalog provides metadata about all known components
var ComponentCatalog = map[string]ComponentType{
	"ai.anonymizer": ComponentTypeAnonymizer,
	"ai.completions": ComponentTypeAI,
	"ai.embeddings": ComponentTypeAI,
	"ai.service": ComponentTypeAI,
	"chat.repository": ComponentTypeRepository,
	"database.postgresql": ComponentTypeDatabase,
	"directory.watcher": ComponentTypeDirectory,
	"embedding.wrapper": ComponentTypeEmbedding,
	"evolving.memory": ComponentTypeMemory,
	"fx.framework": ComponentTypeUtility,
	"graphql.server": ComponentTypeServer,
	"holon.manager": ComponentTypeManager,
	"holon.service.main": ComponentTypeService,
	"infrastructure.config": ComponentTypeUtility,
	"infrastructure.main": ComponentTypeUtility,
	"main.startup": ComponentTypeUtility,
	"mcp.service": ComponentTypeMCP,
	"memory.storage": ComponentTypeMemory,
	"nats.client": ComponentTypeNATS,
	"nats.server": ComponentTypeNATS,
	"services.background": ComponentTypeUtility,
	"sqlite.queries": ComponentTypeDatabase,
	"sqlite.store": ComponentTypeDatabase,
	"telegram.service": ComponentTypeTelegram,
	"temporal.client": ComponentTypeTemporal,
	"temporal.scheduler": ComponentTypeTemporal,
	"temporal.worker": ComponentTypeTemporal,
	"tools.application": ComponentTypeUtility,
	"tools.registry": ComponentTypeUtility,
	"tts.service": ComponentTypeTTS,
	"twinchat.service": ComponentTypeTwinChat,
	"whatsapp.service": ComponentTypeWhatsApp,
}

// ComponentSources maps component IDs to their source locations
var ComponentSources = map[string]string{
	"ai.anonymizer": "pkg/bootstrap/components_generated.go:14",
	"ai.completions": "pkg/bootstrap/fx/ai.go:60",
	"ai.embeddings": "pkg/bootstrap/fx/ai.go:85",
	"ai.service": "pkg/bootstrap/components_generated.go:11",
	"chat.repository": "pkg/bootstrap/fx/services.go:59",
	"database.postgresql": "pkg/bootstrap/components_generated.go:17",
	"directory.watcher": "pkg/bootstrap/components_generated.go:22",
	"embedding.wrapper": "pkg/bootstrap/fx/database.go:36",
	"evolving.memory": "pkg/bootstrap/fx/memory.go:36",
	"fx.framework": "pkg/bootstrap/components_generated.go:65",
	"graphql.server": "pkg/bootstrap/components_generated.go:45",
	"holon.manager": "pkg/holon/manager.go:79",
	"holon.service.main": "pkg/holon/service.go:46",
	"infrastructure.config": "pkg/bootstrap/fx/infrastructure.go:59",
	"infrastructure.main": "pkg/bootstrap/components_generated.go:67",
	"main.startup": "pkg/bootstrap/components_generated.go:68",
	"mcp.service": "pkg/bootstrap/components_generated.go:28",
	"memory.storage": "pkg/bootstrap/fx/database.go:62",
	"nats.client": "pkg/bootstrap/fx/infrastructure.go:99",
	"nats.server": "pkg/bootstrap/fx/infrastructure.go:78",
	"services.background": "pkg/bootstrap/components_generated.go:69",
	"sqlite.queries": "pkg/bootstrap/fx/infrastructure.go:155",
	"sqlite.store": "pkg/bootstrap/fx/infrastructure.go:126",
	"telegram.service": "pkg/bootstrap/components_generated.go:54",
	"temporal.client": "pkg/bootstrap/fx/temporal.go:53",
	"temporal.scheduler": "pkg/bootstrap/components_generated.go:58",
	"temporal.worker": "pkg/bootstrap/components_generated.go:59",
	"tools.application": "pkg/bootstrap/components_generated.go:70",
	"tools.registry": "pkg/bootstrap/components_generated.go:71",
	"tts.service": "pkg/bootstrap/fx/services.go:124",
	"twinchat.service": "pkg/bootstrap/components_generated.go:62",
	"whatsapp.service": "pkg/bootstrap/components_generated.go:74",
}
