version: "2"

# Fast configuration for PR linting
linters:
  default: none
  enable:
    # Fast linters that catch important issues
    - errcheck      # Checks for unchecked errors - Fast and critical
    - ineffassign   # Detects ineffectual assignments - Fast
    - misspell      # Finds commonly misspelled English words [auto‑fix] - Fast
    - whitespace    # Detects trailing whitespace [auto‑fix] - Fast
    - godot         # Checks if comments end in a period [auto‑fix] - Fast
    - nolintlint    # Reports ill‑formed or insufficient nolint directives [auto‑fix] - Fast
    - unconvert     # Remove unnecessary type conversions [auto‑fix] - Fast
    - nakedret      # Finds naked returns - Fast
    - durationcheck # Checks for two durations multiplied together - Fast
    
    # Skip these slow linters for PRs (run on main branch only):
    # - govet (especially with enable-all: true) - SLOW
    # - staticcheck - VERY SLOW
    # - unused - SLOW (analyzes entire codebase)

linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US
  goconst:
    min-len: 3
    min-occurrences: 3

# Formatter configuration (same as main config)
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/EternisAI/enchanted-twin
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/EternisAI)
    gofmt:
      simplify: true

# Issue handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Output configuration
output:
  sort-order:
    - file

# Run configuration - faster timeout for PR linting
run:
  timeout: 3m  # Shorter timeout for fast linters
  issues-exit-code: 1
  tests: true
  go: "1.24" 