version: "2"

# Ultra-minimal configuration for PR linting - only the most critical linters
linters:
  default: none
  enable:
    # Only the fastest, most critical linters
    - errcheck      # Critical: unchecked errors can cause runtime panics
    - ineffassign   # Fast: catches dead assignments
    - misspell      # Very fast: spelling in comments/strings [auto‑fix]
    
    # Removed for speed (run on main branch only):
    # - whitespace, godot, nolintlint, unconvert, nakedret, durationcheck
    # - govet (with enable-all: true) - SLOW
    # - staticcheck - VERY SLOW  
    # - unused - SLOW (analyzes entire codebase)

  settings:
    errcheck:
      check-type-assertions: true
    misspell:
      locale: US



# Issue handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Output configuration
output:
  sort-order:
    - file

# Run configuration - reasonable timeout for minimal linters
run:
  timeout: 5m  # Enough time for package loading + minimal linting
  issues-exit-code: 1
  tests: true
  go: "1.24" 