# Docker Compose configuration for TDLib services

services:
  tdlib-service:
    build:
      context: .
      dockerfile: tdlib.Dockerfile
    container_name: enchanted-twin-tdlib-service
    volumes:
      - tdlib-db:/tdlib/db
      - tdlib-files:/tdlib/files
    environment:
      - TELEGRAM_TDLIB_API_ID=${TELEGRAM_TDLIB_API_ID}
      - TELEGRAM_TDLIB_API_HASH=${TELEGRAM_TDLIB_API_HASH}
      - TELEGRAM_TDLIB_DB_DIR=/tdlib/db
      - TELEGRAM_TDLIB_FILES_DIR=/tdlib/files
      - PORT=9090
    ports:
      - "9090:9090"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - enchanted-twin-network

networks:
  enchanted-twin-network:
    driver: bridge

volumes:
  tdlib-db:
  tdlib-files:
