name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          
      - name: Install yq
        env:
          YQ_VERSION: "v4.44.1"          # 📌 bump intentionally on updates
          YQ_SHA256: "6dc2d0cd4e0caca5aeffd0d784a48263591080e4a0895abe69f3a76eb50d1ba3"
        run: |
          curl -L -o yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          echo "${YQ_SHA256}  yq" | sha256sum -c -
          sudo install -m0755 yq /usr/local/bin/yq
          rm yq
      - name: Generate auto-request-review config
        run: |
          cat > .github/auto_request_review.yml << EOF
          groups:
            frontend: 
          $(yq -r '.teams.frontend[]' .github/teams.yml | sed 's/^/      - /')
            mcp:
          $(yq -r '.teams.mcp[]' .github/teams.yml | sed 's/^/      - /')
            memory:
          $(yq -r '.teams.memory[]' .github/teams.yml | sed 's/^/      - /')
            agent:
          $(yq -r '.teams.agent[]' .github/teams.yml | sed 's/^/      - /')
            data_ingestion:
          $(yq -r '.teams.data_ingestion[]' .github/teams.yml | sed 's/^/      - /')
            anonymiser:
          $(yq -r '.teams.anonymiser[]' .github/teams.yml | sed 's/^/      - /')
            holon:
          $(yq -r '.teams.holon[]' .github/teams.yml | sed 's/^/      - /')
            twinchat:
          $(yq -r '.teams.twinchat[]' .github/teams.yml | sed 's/^/      - /')
            github:
          $(yq -r '.teams.github[]' .github/teams.yml | sed 's/^/      - /')
          
          options:
            ignore_draft: true
            ignore_paths:
              - '**.md'
          
          rules:
            - name: Frontend changes
              condition:
                files:
                  - 'app/**'
              reviewers:
                groups:
                  - frontend
                users: []
              random_count: 1
            - name: MCP changes  
              condition:
                files:
                  - 'backend/golang/pkg/mcpserver/**'
              reviewers:
                groups:
                  - mcp
                users: []
              random_count: 1
            - name: Memory changes
              condition:
                files:
                  - 'backend/golang/pkg/agent/memory/**'
              reviewers:
                groups:
                  - memory
                users: []
              random_count: 1
            - name: Agent changes
              condition:
                files:
                  - 'backend/golang/pkg/agent/**'
              reviewers:
                groups:
                  - agent
                users: []
              random_count: 1
            - name: Data ingestion changes
              condition:
                files:
                  - 'backend/golang/pkg/dataprocessing/**'
              reviewers:
                groups:
                  - data_ingestion
                users: []
              random_count: 1
            - name: Anonymiser changes
              condition:
                files:
                  - 'backend/golang/pkg/ai/**'
              reviewers:
                groups:
                  - anonymiser
                users: []
              random_count: 1
            - name: Holon changes
              condition:
                files:
                  - 'backend/golang/pkg/holon/**'
              reviewers:
                groups:
                  - holon
                users: []
              random_count: 1
            - name: TwinChat changes
              condition:
                files:
                  - 'backend/golang/pkg/twinchat/**'
              reviewers:
                groups:
                  - twinchat
                users: []
              random_count: 1
            - name: GitHub/CI changes
              condition:
                files:
                  - '.github/**'
              reviewers:
                groups:
                  - github
                users: []
              random_count: 1
          EOF
          
      - name: Auto-assign reviewers
        uses: necojackarc/auto-request-review@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/auto_request_review.yml