name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          
      - name: Install yq
        env:
          YQ_VERSION: "v4.44.1"          # 📌 bump intentionally on updates
          YQ_SHA256: "6dc2d0cd4e0caca5aeffd0d784a48263591080e4a0895abe69f3a76eb50d1ba3"
        run: |
          curl -L -o yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          echo "${YQ_SHA256}  yq" | sha256sum -c -
          sudo install -m0755 yq /usr/local/bin/yq
          rm yq
      - name: Generate auto-assign configs from teams.yml
        run: |
          # Generate config files using yq
          for team in frontend mcp memory agent data_ingestion anonymiser holon twinchat github default; do
            team_file=$(echo $team | tr '_' '-')
            cat > .github/auto-assign-${team_file}.yml << EOF
          skipDraft: true
          addReviewers: true
          addAssignees: false
          numberOfReviewers: 1
          skipKeywords: ['[skip ci]', '[skip review]']
          reviewers:
          $(yq -r ".teams.${team}[]" .github/teams.yml | sed 's/^/  - /')
          EOF
          done
          
      - name: Load teams for self-assignment prevention
        id: teams
        run: |
          echo "frontend=$(yq -r '.teams.frontend | join("\" \"")' .github/teams.yml)" >> $GITHUB_OUTPUT
          echo "mcp=$(yq -r '.teams.mcp | join("\" \"")' .github/teams.yml)" >> $GITHUB_OUTPUT
          
      - name: Check changed paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            frontend:
              - 'app/**'
            mcp:
              - 'backend/golang/pkg/mcpserver/**'
            memory:
              - 'backend/golang/pkg/agent/memory/**'
            agent:
              - 'backend/golang/pkg/agent/**'
            data_ingestion:
              - 'backend/golang/pkg/dataprocessing/**'
            anonymiser:
              - 'backend/golang/pkg/ai/**'
            holon:
              - 'backend/golang/pkg/holon/**'
            twinchat:
              - 'backend/golang/pkg/twinchat/**'
            github:
              - '.github/**'
              
      - name: Auto-assign reviewers - Frontend
        if: steps.filter.outputs.frontend == 'true' && !contains(steps.teams.outputs.frontend, github.actor)
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-frontend.yml'
          
      - name: Auto-assign reviewers - MCP  
        if: steps.filter.outputs.mcp == 'true' && !contains(steps.teams.outputs.mcp, github.actor)
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-mcp.yml'
          
      - name: Auto-assign reviewers - Memory
        if: steps.filter.outputs.memory == 'true' && steps.filter.outputs.agent != 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-memory.yml'
          
      - name: Auto-assign reviewers - Agent
        if: steps.filter.outputs.agent == 'true' && steps.filter.outputs.memory != 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-agent.yml'
          
      - name: Auto-assign reviewers - Data Ingestion
        if: steps.filter.outputs.data_ingestion == 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-data-ingestion.yml'
          
      - name: Auto-assign reviewers - Anonymiser
        if: steps.filter.outputs.anonymiser == 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-anonymiser.yml'
          
      - name: Auto-assign reviewers - Holon
        if: steps.filter.outputs.holon == 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-holon.yml'
          
      - name: Auto-assign reviewers - TwinChat
        if: steps.filter.outputs.twinchat == 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-twinchat.yml'
          
      - name: Auto-assign reviewers - GitHub/CI
        if: steps.filter.outputs.github == 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-github.yml'
          
      - name: Auto-assign reviewers - Default
        if: |
          steps.filter.outputs.frontend != 'true' &&
          steps.filter.outputs.mcp != 'true' &&
          steps.filter.outputs.memory != 'true' &&
          steps.filter.outputs.agent != 'true' &&
          steps.filter.outputs.data_ingestion != 'true' &&
          steps.filter.outputs.anonymiser != 'true' &&
          steps.filter.outputs.holon != 'true' &&
          steps.filter.outputs.twinchat != 'true' &&
          steps.filter.outputs.github != 'true'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign-default.yml'